### ISSUE TITLE
Game crashed when it tried to load the main menu.

### ISSUE THREAD

**Issue by GeneralDelphox** [Nepgearsy/Nepgearsy-Main-Menu#4]
Application has crashed: C++ exception
mods/Nepgearsy Main Menu/lib/NewHeistsGui.lua:7: attempt to index field '_content_panel' (a nil value)

SCRIPT STACK

Update() @mods/base/req/core/DelayedCalls.lua:24
func() @mods/base/req/core/DelayedCalls.lua:6
Call() @mods/base/req/core/Hooks.lua:109
update() @mods/base/lua/MenuSetup.lua:7
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.83.455.
	CPU : Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 920M / nvd3dum.dll[22.21.13.8477]
	Language : english
	Memory :     8102MB 452KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers / Headphones (Realtek High Definition Audio))

I'm suspecting this is caused by a conflict between this mod and RSS ingame.
https://modworkshop.net/mydownloads.php?action=view_down&did=16986

**Comment by AzureeDev** [comment]
I tried running RSS ingame and my mod in the same time, no problem with it.
Do you have any other mod messing with the content update thing?

EDIT: Try to download the last version here.
