### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ElReyZero** [Nepgearsy/Nepgearsy-Main-Menu#7]
Application has crashed: C++ exception
mods/base/req/utils/json-0.9.lua:372: Unexpected character at Line 1 character 1: ï (239) when reading object ({ or [ or ' or " or number or boolean or null expected)
Context: 
ï»¿{
	"NepgearsyMM_Title" : "Op
^

Just deleted the extra E from the text and now it crashes

**Comment by ElReyZero** [comment]
Also which program do you use to code this because both notepad and notepad++ are causing thi errors to occur

**Comment by AzureeDev** [comment]
I'm using sublime text

Also it seems that there is no error at all
